# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97d537de4646ff79844548c7dd0a5362"
name = "checkout-extensibility"
handle = "checkout-extensibility-89"
application_url = "https://travel-levitra-streams-nylon.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pruebas-equipo-web.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_checkouts, read_checkouts, write_orders"

[auth]
redirect_urls = [
  "https://travel-levitra-streams-nylon.trycloudflare.com/auth/callback",
  "https://travel-levitra-streams-nylon.trycloudflare.com/auth/shopify/callback",
  "https://travel-levitra-streams-nylon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
